name: Manual Historical Download (SQLAlchemy)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Memberikan izin tambahan secara eksplisit
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Update ke v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Update ke v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install yfinance pandas sqlalchemy

      - name: Run Downloader
        run: python download_data.py
        
      - name: View Database Content # Langkah baru untuk melihat isi
        run: python view_data.py

      - name: Run Analysis
        run: python analysis.py  

      - name: Commit and Push Database
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add database_investasi.db
          # Perbaikan agar tidak error jika tidak ada data baru
          git commit -m "Update database: $(date)" || echo "No changes to commit"
          git push
